rabbitmq:
    properties:
        common:
            host: 192.168.3.161
            port: 5672
            connection-timeout.seconds: 5
            cache.connection.mode: connection
            cache.connection.size: 10
        may:
            host: 192.168.3.161
            port: 5672
            connection-timeout.seconds: 5
            cache.connection.mode: connection
            cache.connection.size: 10

user-service-exchange: xfm-userServiceExchange
user.update.exchange: account.update.topic

id:
    passport: passport.uid
    device: passport.user.device.id

moon.bp-id:
    login_rate:
        app: 34
        web: 34
    login_safe:
        app: 108
        web: 108
    reset_pwd:
        app: 77
        web: 77
    register:
        app: 195
        web: 195

kafka.topic.friendship: friendship-source

mybatis:
    check-config-location: true
    configuration:
        auto-mapping-unknown-column-behavior: warning
        cache-enabled: false
        local-cache-scope: statement
        map-underscore-to-camel-case: true
pagehelper:
    helper-dialect: mysql
    page-size-zero: false
    reasonable: true
    support-methods-arguments: true

spring:
    kafka:
        bootstrap-servers: 192.168.3.44:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            acks: -1
    datasource:
        druid:
            initial-size: 5
            max-active: 20
            max-wait: 2000
            min-evictable-idle-time-millis: 300000
            min-idle: 10
            password: password!
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 300000
            url: jdbc:mysql://192.168.60.11:3306/awww?useUnicode=true&character_set_server=utf8mb4&zeroDateTimeBehavior=convertToNull
            username: username
            validation-query: SELECT 1
    redis:
        host: 192.168.60.47
        port: 6380
        password: password
        database: 0
        timeout: 5000ms
        jedis:
            pool:
                max-idle: 20
                min-idle: 20
                max-active: 20
                max-wait: 1200ms
